### ISSUE TITLE
Insert metadata to a video file

### ISSUE THREAD

**Issue by aleksey2403** [Synopsis/Synopsis#34]
Hello,

Following the comment [here](https://github.com/google/spatial-media/issues/65) I am trying to understand how to use this library for inserting a metadata to .mp4 video file.

Basically, I need to insert an xml file to the following box: moov.trak.uuid
where uuid is ffcc8263-f855-4a93-8814-587a02521fdd.

I have read wiki discussions but I haven't found the answer.

Thanks for any help!

Alex

**Comment by vade** [comment]
Sorry - I totally missed this till now.

basically, you need :
* a library that can write UUID's into the appropriate mood atom as you stated. A modified libMP4v2 can do that. I've done a little something for this project that is similar, but not the same.

Take a look at the latest few commits here.

https://github.com/Synopsis/mp4v2/commits/master
